# Generated by Django 3.0.8 on 2020-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200716_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivary', 'Out for delivary'), ('Delivered', 'Delivered')], max_length=120, null=True),
        ),
    ]
