# Generated by Django 3.0.8 on 2020-07-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200719_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile-pic.png', null=True, upload_to='images/'),
        ),
    ]
